Use new parameter name
cloudbees-io/publish-evidence-item pull request #11
Opened 2024-07-24 00:27 UTC by gmaxey

2024-07-25 11:39 UTC, karakurty requested changes
@gmaxey is not enough to rename input parameter in the workflow file, please do the same in the action definition file as well.

2024-07-25 14:58 UTC, gmaxey commented
Yes, please approve my three PRs. Yes, should have had only one branch for the parameter name changes

2024-07-25 15:05 UTC, karakurty approved these changes

2024-07-29 17:21 UTC, gmaxey commented
@karakurty please merge

2024-08-05 18:38 UTC, merged